<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Mz40zBc' shared service.

return $this->privates['.service_locator.Mz40zBc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'data' => ['privates', '.errored..service_locator.Mz40zBc.App\\Entity\\Order', NULL, 'Cannot autowire service ".service_locator.Mz40zBc": it references class "App\\Entity\\Order" but no such service exists.'],
]);
