<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIoApCx1\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIoApCx1/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIoApCx1.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIoApCx1\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerIoApCx1\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'IoApCx1',
    'container.build_id' => '69738354',
    'container.build_time' => 1558685285,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIoApCx1');
